<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);NU1603;NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <!-- Tầng kiến trúc (Clean Architecture) -->
    <ProjectReference Include="..\CulinaryBlog.Application\CulinaryBlog.Application.csproj" />
    <ProjectReference Include="..\CulinaryBlog.Infrastructure\CulinaryBlog.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- API & Cấu hình Swagger/Scalar -->
    <PackageReference Include="Carter" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <!-- EF Core & Database PostgreSQL -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <!-- Ghi đè xung đột phiên bản Roslyn từ EF Core Design 9.0 -->
    <PackageReference Include="Microsoft.CodeAnalysis.Common" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" />
    
   
  </ItemGroup>

</Project>